#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE    bApplyOn;
		long    lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
#ifdef ENABLE_WOLFMAN_CHARACTER
	AFFECT_BLEEDING,		// 227
#endif
#ifdef __ENABLE_COLLECTIONS_SYSTEM__
	AFFECT_COLLECTIONS0 = 303,
	AFFECT_COLLECTIONS1 = 304,
	AFFECT_COLLECTIONS2 = 305,
	AFFECT_COLLECTIONS3 = 306,
	AFFECT_COLLECTIONS4 = 307,
	AFFECT_COLLECTIONS5 = 308,
	AFFECT_COLLECTIONS6 = 309,
#endif
	AFFECT_COLLECT_BIOLOG = 310,
	AFFECT_COLLECT_KOLEKCJONER = 311,
	AFFECT_COLLECT_POLOWANIE = 312,
	AFFECT_COLLECT_BOSSOLOGIA = 313,
	AFFECT_COLLECT_METINOLOGIA = 314,
	AFFECT_COLLECT_KOLEKCJONER_EXTRA = 315,

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,
	AFFECT_ITEM_BONUS		= 501,
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,
	AFFECT_GOLD_BONUS		= 506,
	AFFECT_PICKUP			= 507,
#ifdef __PREMIUM_PRIVATE_SHOP__
	AFFECT_PREMIUM_PRIVATE_SHOP = 508,
#endif
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,
	AFFECT_NO_DEATH_PENALTY	= 511,
	AFFECT_SKILL_BOOK_BONUS	= 512,  // Rada 
	AFFECT_SKILL_NO_BOOK_DELAY	= 513, // Egzo

	AFFECT_HAIR	= 514,
	AFFECT_EXP_BONUS_EURO_FREE = 516,
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_SKILE_PAS_BOOK_BONUS	= 519,  // Rada Pasywne
	AFFECT_SKILE_PAS_NO_BOOK_DELAY	= 520,// Egzo Pasywne
	
	AFFECT_SKILE_PET_BOOK_BONUS	= 521,
	AFFECT_SKILE_PET_NO_BOOK_DELAY	= 522,
	
	AFFECT_SKILE_BUFF_BOOK_BONUS	= 523,
	AFFECT_SKILE_BUFF_NO_BOOK_DELAY	= 524,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND = 537,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_BLEND_FISH = 545,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,
#ifdef ENABLE_EXTENDED_BLEND
	AFFECT_MALL_EX = 548,
	AFFECT_WATER = 549,
	AFFECT_BLEND_EX = 550,
#endif
#ifdef ENABLE_SKILE_PASYWNE
	AFFECT_PASYWKI_EXTRABONUS = 551,
#endif
#ifdef ENABLE_ALIGN_RENEWAL
	AFFECT_ALIGN_BONUS1 = 900,
	AFFECT_ALIGN_BONUS2 = 901,
	AFFECT_ALIGN_BONUS3 = 902,
	AFFECT_ALIGN_BONUS4 = 903,
#endif
	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING	   = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,
#ifdef ENABLE_EXTRABONUS_SYSTEM
#ifdef ENABLE_NEW_PET_SYSTEM
	AFFECT_NEW_PET = 554,
#endif
	AFFECT_NEW_PET_EXTRABONUS0 = 555,
	AFFECT_NEW_PET_EXTRABONUS1 = 556,
	AFFECT_NEW_PET_EXTRABONUS2 = 557,
#endif
#ifdef TITLE_SYSTEM_BYLUZER
	AFFECT_TITLES = 568,
#endif
#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	AFFECT_NEW_MOUNT = 800,
#endif
#ifdef ENABLE_EXTRABONUS_SYSTEM
#ifdef ENABLE_SYSTEM_RUNE
	AFFECT_RUNE = 740,
	AFFECT_RUNE_RED = 741,
	AFFECT_RUNE_BLUE = 742,
	AFFECT_RUNE_GREEN = 743,
	AFFECT_RUNE_YELLOW = 744,
	AFFECT_RUNE_BLACK = 745,
#endif
	AFFECT_RUNE_DECK5 = 746,
	AFFECT_RUNE_DECK9 = 747,
#endif
#ifdef ENABLE_EXTRABONUS_SYSTEM
#ifdef ENABLE_GLOVE_SYSTEM
	AFFECT_GLOVE_BONUS = 748,
#endif
#endif
#ifdef __AUTO_QUQUE_ATTACK__
	AFFECT_AUTO_METIN_FARM = 706,
#endif
	AFFECT_MIKSTURA_MADROSCI = 750,
	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE, // 0 
	AFF_YMIR, // 1
	AFF_INVISIBILITY, // 2
	AFF_SPAWN, // 3
	AFF_POISON, //4 
	AFF_SLOW,//5
	AFF_STUN,//6
	AFF_DUNGEON_READY,//7
	AFF_DUNGEON_UNIQUE,//8
	AFF_BUILDING_CONSTRUCTION_SMALL,//9
	AFF_BUILDING_CONSTRUCTION_LARGE,//10
	AFF_BUILDING_UPGRADE,//11
	AFF_MOV_SPEED_POTION,//12
	AFF_ATT_SPEED_POTION,//13
	AFF_FISH_MIND,//14
	AFF_JEONGWIHON,//15
	AFF_GEOMGYEONG,//16
	AFF_CHEONGEUN,//17
	AFF_GYEONGGONG,//18
	AFF_EUNHYUNG,//19
	AFF_GWIGUM,//20
	AFF_TERROR,//21
	AFF_JUMAGAP,//22
	AFF_HOSIN,//23
	AFF_BOHO,//24
	AFF_KWAESOK,//25
	AFF_MANASHIELD,//26
	AFF_MUYEONG,//27
	AFF_REVIVE_INVISIBLE,//28
	AFF_FIRE,//29
	AFF_GICHEON,//30
	AFF_JEUNGRYEOK,//31
	AFF_TANHWAN_DASH,//32
	AFF_PABEOP,//33
	AFF_CHEONGEUN_WITH_FALL,//34
	AFF_POLYMORPH,//35
	AFF_WAR_FLAG1,//36
	AFF_WAR_FLAG2,//37
	AFF_WAR_FLAG3,//38
	AFF_CHINA_FIREWORK,
	AFF_HAIR,
	// AFF_GERMANY,
	// AFF_RAMADAN_RING,
	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
//martysama0134's ceqyqttoaf71vasf9t71218
