#ifndef __INC_PYTHON_uiscriptlib_MANAGER_H__
#define __INC_PYTHON_uiscriptlib_MANAGER_H__
#define inituiscriptlibManager inituiscriptlib
/* uiscriptlib module */
/* uiscriptlib.isExist */
/* uiscriptlib.moduleImport */
/* uiscriptlib.getList */
/* this lib includes modules under this lines.
	acceptguildwardialog
	Acce_AbsorbWindow
	Acce_CombineWindow
	ArtefaktSystemWindow
	AtlasWindow
	AttachStoneDialog
	Aura_AbsorbWindow
	Aura_LevelUpWindow
	BattlepassDialog
	BeltInventoryWindow
	Bonus
	BonusChanger
	BuffNpcCreateWindow
	BuffNpcRenameWindow
	BuffNpcSelectSkillWindow
	BuffNpcWindow
	BuffNpcWindow_new
	BuildGuildBuildingWindow
	ChangeGradeNameDialog
	ChangePasswordDialog
	CharacterWindow
	ChatSettingWindow
	ChestDropInfoWindow
	CollectionsWindow
	CollectWindow
	ConnectingDialog
	CostumeWindow
	CreateCharacterWindow
	CubeRenewalWindow
	CubeResultWindow
	CubeWindow
	DeclareGuildWarDialog
	DepoIsWindow
	DopalaczeWindow
	DragonSoulRefineWindow
	DragonSoulWindow
	DungeonInfoWindow
	DungeonRankingWindow
	EquipmentDialog
	EventCalendar
	ExchangeDialog
	ExpandedMoneyTaskBar
	ExpandedTaskBar
	ExtendedInventoryWindow
	FastEquip
	FishingWindow
	GameOptionDialog
	GameOptionDialog_forMobile
	GameWindow
	GiftCodeWindow
	GuildWindow
	GuildWindow_BaseInfoPage
	GuildWindow_BoardPage
	GuildWindow_GradePage
	GuildWindow_GuildInfoPage
	GuildWindow_GuildInfoPage_Eu
	GuildWindow_GuildInfoPage_Jp
	GuildWindow_GuildSkillPage
	GuildWindow_MemberPage
	HelpWindow
	HelpWindow2
	HorseShoe
	Ikonki
	IMEKOR
	InputDialog
	InputDialogWithDescription
	InputDialogWithDescription2
	InventoryWindow
	InventoryWindowEx
	ItemShopEditorWindow
	ItemShopPopUpDialog
	ItemShopSelectAttributeDialog
	ItemShopSelectList
	ItemShopWindow
	KeyChange_Window
	LoadingWindow
	LocationRenderMapDialog
	LocationWindow
	MallWindow
	MapaSw
	MarkListWindow
	Marmur_Window
	MessengerWindow
	MiniGameRumiGamePage
	MiniGameRumiWaitingPage
	MiniGameWindow
	MiniMap
	MiniMapDungeonInfo
	MoneyInputDialog
	Mount_Window
	MouseButtonWindow
	MoveChannelDialog
	MusicListWindow
	OdlamkiWindow
	PartyMemberInfoBoard
	PasswordDialog
	PickEtcDialog
	PickEtcDialog2
	PickMoneyDialog
	PopUpDialog
	PrivateShopBuilder
	QuestDialog
	QuestionDialog
	QuestionDialog2
	QueueWindow
	RefineDialog
	RemoveItemDialog
	RespDialog
	RespMiniMapDialog
	RespRenderMapDialog
	RespRenderTargetDialog
	RestartDialog
	RightMouseButtonWindow
	RuneWindow
	SafeBoxWindow
	SelectCharacterWindow
	SelectEmpireWindow
	SelectItemWindow
	ShopDialog
	ShopSearch
	SkillChooseWindow
	SkillPointResetDialog
	StoneDetach
	SystemDialog
	SystemDialog_forMall
	SystemDialog_forPortal
	SystemOptionDialog
	SystemsWindow
	SystemsWindow_new
	TaskBar
	WarteSchleife
	WebWindow
	WeeklyRank
	WhisperDialog
	WonExchangeWindow
	_Pety_script
*/
void inituiscriptlibManager();
#endif
