# import uiScriptLocale

window = {
	"name" : "SystemsWindow",
	"x" : SCREEN_WIDTH - 190 - 148, #176
	"y" : SCREEN_HEIGHT - 55 - 565 + 209 + 32 - 37, #37
	"width" : 140, #148
	"height" : 450, #139
	"type" : "window",
	"children" :
	(
		{
			"name" : "ExpandBtn",
			"type" : "button",
			"x" : -6,
			"y" : 69,
			"default_image" : "locale/pl/ui/config/btn_expand_normal.tga",
			"over_image" : "locale/pl/ui/config/btn_expand_over.tga",
			"down_image" : "locale/pl/ui/config/btn_expand_down.tga",
			"disable_image" : "locale/pl/ui/config/btn_expand_disabled.tga",
		},
		{
			"name" : "SystemsWindowLayer",
			"x" : 5,
			"y" : 0,
			"width" : 140,
			"height" : 450, #139
			"children" :
			(
				{
				 	"name" : "BiologButton",
				 	"type" : "button",

				 	"x" : 50,
				 	"y" : 330,
					
				 	"default_image" : "icon/button_new/biolog_button0.png",
				 	"over_image" : "icon/button_new/biolog_button1.png",
				 	"down_image" : "icon/button_new/biolog_button2.png",
				},
				{
				 	"name" : "ZlomiarzButton",
				 	"type" : "button",

				 	"x" : 50,
				 	"y" : 330+60,
					
				 	"default_image" : "icon/button_new/zlomiarz_button0.png",
				 	"over_image" : "icon/button_new/zlomiarz_button1.png",
				 	"down_image" : "icon/button_new/zlomiarz_button2.png",
				},
				{
					"name" : "MinimizeBtn",
					"type" : "button",
					"x" : 2,
					"y" : 69,
					"width" : 10,
					"default_image" : "locale/pl/ui/config/btn_minimize_normal.tga",
					"over_image" : "locale/pl/ui/config/btn_minimize_over.tga",
					"down_image" : "locale/pl/ui/config/btn_minimize_down.tga",
					"disable_image" : "locale/pl/ui/config/btn_minimize_disabled.tga",
				},
				{
					"name" : "SystemsWindowBoard",
					"type" : "board",
					"style" : ("attach", "float"),
					"x" : 10,
					"y" : 0,
					"width" : 140,
					"height" : 314, #172
					"children" :
					(
						{
                            "name" : "Mapa_Button",
							"type" : "button",
							"x" : 8,
							"y" : 8,
							"default_image" : "icon/button_new/tp1.png",
							"over_image" : "icon/button_new/tp2.png",
							"down_image" : "icon/button_new/tp3.png",
						},
						{
							"name" : "Localizacja_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8,
							"default_image" : "icon/button_new/zapis1.png",
							"over_image" : "icon/button_new/zapis2.png",
							"down_image" : "icon/button_new/zapis3.png",
						},
						{
							"name" : "OfflineShopButton",
							"type" : "button",
							"x" : 8,
							"y" : 8+33,
							"default_image" : "icon/button_new/offline1.png",
							"over_image" : "icon/button_new/offline2.png",
							"down_image" : "icon/button_new/offline3.png",
						},
						{
							"name" : "aExp_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33,
							"default_image" : "icon/button_new/exp1.png",
							"over_image" : "icon/button_new/exp2.png",
							"down_image" : "icon/button_new/exp3.png",
						},
						{
							"name" : "Dodatkowe_Button",
							"type" : "button",
							"x" : 8,
							"y" : 8+33+33,
							"default_image" : "icon/button_new/podreczny1.png",
							"over_image" : "icon/button_new/podreczny2.png",
							"down_image" : "icon/button_new/podreczny3.png",
						},
						{
							"name" : "Pet_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33+33,
							"default_image" : "icon/button_new/pet1.png",
							"over_image" : "icon/button_new/pet2.png",
							"down_image" : "icon/button_new/pet3.png",
						},
						{
							"name" : "Ranking_Button",
							"type" : "button",
							"x" : 8,
							"y" : 8+33+33+33,
							"default_image" : "icon/button_new/title1.png",
							"over_image" : "icon/button_new/title2.png",
							"down_image" : "icon/button_new/title3.png",
						},
						{
							"name" : "Dopek_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33+33+33,
							"default_image" : "icon/button_new/dopek1.png",
							"over_image" : "icon/button_new/dopek2.png",
							"down_image" : "icon/button_new/dopek3.png",
						},
						{
							"name" : "TabelaBon_Button",
							"type" : "button",
							"x" : 8,
							"y" : 8+33+33+33+33,
							"default_image" : "icon/button_new/tabelabon1.png",
							"over_image" : "icon/button_new/tabelabon2.png",
							"down_image" : "icon/button_new/tabelabon3.png",
						},
						{
							"name" : "Switcher_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33+33+33+33,
							"default_image" : "icon/button_new/tabela1.png",
							"over_image" : "icon/button_new/tabela2.png",
							"down_image" : "icon/button_new/tabela3.png",
						},
						{
							"name" : "Shaman_Button",
						 	"type" : "button",
						 	"x" : 8,
						 	"y" : 8+33+33+33+33+33,
						 	"default_image" : "icon/button_new/shaman1.png",
						 	"over_image" : "icon/button_new/shaman2.png",
						 	"down_image" : "icon/button_new/shaman3.png",
						},
						{
						 	"name" : "Marmur_Button",
						 	"type" : "button",
						 	"x" : 9+32,
						 	"y" : 8+33+33+33+33+33,
						 	"default_image" : "icon/button_new/poli1.png",
						 	"over_image" : "icon/button_new/poli2.png",
						 	"down_image" : "icon/button_new/poli3.png",
						},
						{
							"name" : "BossTp_Button",
							"type" : "button",
							"x" : 8,
                            "y" : 8+33+33+33+33+33+33,
							"default_image" : "icon/button_new/tpboss1.png",
							"over_image" : "icon/button_new/tpboss2.png",
							"down_image" : "icon/button_new/tpboss3.png",
						},	
						{
							"name" : "Artefakt_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33+33+33+33+33+33,
							"default_image" : "icon/button_new/rune1.png",
							"over_image" : "icon/button_new/rune2.png",
							"down_image" : "icon/button_new/rune3.png",
						},				
                        {
							"name" : "Kosz_Button",
							"type" : "button",
							"x" : 9,
							"y" : 8+33+33+33+33+33+33+33,
							"default_image" : "icon/button_new/kosz1.png",
							"over_image" : "icon/button_new/kosz2.png",
							"down_image" : "icon/button_new/kosz3.png",
						},
						{
							"name" : "Rune_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33+33+33+33+33+33+33,
							"default_image" : "icon/button_new/artefakt1.png",
							"over_image" : "icon/button_new/artefakt2.png",
							"down_image" : "icon/button_new/artefakt3.png",
						},		
                        {
							"name" : "Mount_Button",
							"type" : "button",
							"x" : 9,
							"y" : 8+33+33+33+33+33+33+33+33,
							"default_image" : "icon/button_new/mount1.png",
							"over_image" : "icon/button_new/mount2.png",
							"down_image" : "icon/button_new/mount3.png",
						},
						{
							"name" : "Dung_Button",
							"type" : "button",
							"x" : 9+32,
							"y" : 8+33+33+33+33+33+33+33+33,
							"default_image" : "icon/button_new/dung1.png",
							"over_image" : "icon/button_new/dung2.png",
							"down_image" : "icon/button_new/dung3.png",
						},	
					),
				},
			)
		},
	),
}
